apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: default
  labels:
    app: kafka-service
spec:
  selector:
    app: broker-service
  ports:
    - name: broker-service
      protocol: TCP
      port: 9092
      targetPort: 9092