swagger: '2.0'
info:
  description: Documentation RMS API v1
  version: '1'
  title: Resource Management System API
host: '192.168.39.74:30008'
basePath: /resource-management/v1
tags:
  - name: caterer-controller
    description: Caterer Controller
produces:
  - application/json
paths:
  /caterer:
    post:
      tags:
        - caterer-controller
      summary: saveCaterer
      operationId: saveCatererUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: caterer
          description: caterer
          required: true
          schema:
            $ref: '#/definitions/CatererRequest'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/caterer/all/{cityName}':
    get:
      tags:
        - caterer-controller
      summary: getCaterersListByCityName
      operationId: getCaterersListByCityNameUsingGET
      produces:
        - application/json
      parameters:
        - name: cityName
          in: path
          description: cityName
          required: true
          type: string
        - name: page
          in: query
          description: page
          required: true
          type: integer
          format: int32
        - name: size
          in: query
          description: size
          required: false
          type: integer
          default: 5
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Page'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/caterer/{name}':
    get:
      tags:
        - caterer-controller
      summary: getCatererById
      operationId: getCatererByIdUsingGET
      produces:
        - application/json
      parameters:
        - name: name
          in: path
          description: name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PersistedCaterer'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Address:
    type: object
    properties:
      city:
        type: string
      postalCode:
        type: string
      street:
        type: string
    title: Address
  AddressImpl:
    type: object
    properties:
      city:
        type: string
      postalCode:
        type: string
      street:
        type: string
    title: AddressImpl
  Capacity:
    type: object
    properties:
      maxGuests:
        type: integer
        format: int32
      minGuests:
        type: integer
        format: int32
    title: Capacity
  CapacityModel:
    type: object
    properties:
      maxGuests:
        type: integer
        format: int32
      minGuests:
        type: integer
        format: int32
    title: CapacityModel
  CatererRequest:
    type: object
    properties:
      address:
        $ref: '#/definitions/AddressImpl'
      capacity:
        $ref: '#/definitions/CapacityModel'
      contact:
        $ref: '#/definitions/ContactModel'
      name:
        type: string
    title: CatererRequest
  Contact:
    type: object
    properties:
      email:
        type: string
      mobileNumber:
        type: string
      phoneNumber:
        type: string
    title: Contact
  ContactModel:
    type: object
    properties:
      email:
        type: string
      mobileNumber:
        type: string
      phoneNumber:
        type: string
    title: ContactModel
  Pageable:
    type: object
    properties:
      offset:
        type: integer
        format: int64
      pageNumber:
        type: integer
        format: int32
      pageSize:
        type: integer
        format: int32
      paged:
        type: boolean
      sort:
        $ref: '#/definitions/Sort'
      unpaged:
        type: boolean
    title: Pageable
  Page:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/PersistedCaterer'
      empty:
        type: boolean
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      pageable:
        $ref: '#/definitions/Pageable'
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
    title: Page«PersistedCaterer»
  PersistedCaterer:
    type: object
    properties:
      address:
        $ref: '#/definitions/Address'
      capacity:
        $ref: '#/definitions/Capacity'
      contact:
        $ref: '#/definitions/Contact'
      id:
        type: string
      name:
        type: string
    title: PersistedCaterer
  Sort:
    type: object
    properties:
      empty:
        type: boolean
      sorted:
        type: boolean
      unsorted:
        type: boolean
    title: Sort
