apiVersion: v1
data:
  application.properties: |
    ############# Application config ####################
    server.port=8013
    spring.application.name=resource-management
    server.servlet.context-path=/${spring.application.name}/v1
    ############# MONGO DB config ####################
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=username
    spring.data.mongodb.password=password
    spring.data.mongodb.database=resource_management_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=mongodb

    ############# CORS config ####################
    cors.enable=true
    #comma separated origin list or star(*) to allow all
    cors.allowedorigins=*

    ###################KAKFA config###############
    resource.management.topic.name=resource-management-topic
    resource.management.key=group_id
    kafka.host=kafka-service
    kafka.port=9092

    ################## Kafka Streams configurations #################
    spring.cloud.stream.kafka.binder.brokers=kafka-service
    spring.cloud.stream.bindings.ims-in-stream.destination=resource-management-topic
    spring.cloud.stream.bindings.ims-in-stream.group=group_id
    spring.cloud.stream.bindings.ims-in-stream.content-type=application/json

    caterer.city.name.regex=^[a-zA-Z\s]+$

    ################### Redis Config#############
    redis.host=redis
    redis.port=6379
    redis.is.enabled=true
    redis.city.name.key=CITY
    ################## Get Api Page Config #########
    caterer.get.city.name.api.page.size.default=5
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-30T10:48:06Z"
  name: rms-config
  namespace: default
  resourceVersion: "45701"
  uid: cc5ea5c9-4b02-4944-9c55-b52e3d795c6a