apiVersion: v1
data:
  application.properties: |
    ############### Application config ####################
    server.port=8013
    spring.application.name=resource-management
    server.servlet.context-path=/${spring.application.name}/v1
    ############# MONGO DB config ####################
    spring.data.mongodb.authentication-database=admin
    spring.data.mongodb.username=username
    spring.data.mongodb.password=password
    spring.data.mongodb.database=resource_management_db
    spring.data.mongodb.port=27017
    spring.data.mongodb.host=mongodb
    ############# CORS config ####################
    #comma separated origin list or star(*) to allow all
    cors.allowedorigins=*
    cors.enable=true
    ###################KAKFA config###############
    resource.management.topic.name=resource-management-topic
    kafka.host=kafka-service
    kafka.port=9092
    ################### Redis Config#############
    spring.cache.type=redis
    spring.redis.host=redis
    spring.redis.port=6379
    ################## Get Api Page Config #########
    caterer.get.city.name.api.page.size.default=5
    caterer.city.name.regex=^[a-zA-Z\s]+$
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-01T08:37:46Z"
  name: rms-config
  namespace: default
  resourceVersion: "84780"
  uid: d08dde07-13c8-4ee9-96ca-cd69b411b76d